### PR TITLE
Method densmap dimensionality reduction

### PR DESCRIPTION
**Pull request by bendemeo**
### Submission type

* [ ] This submission adds a new dataset
* [x] This submission adds a new method
* [ ] This submission adds a new metric
* [ ] This submission adds a new task
* [ ] This submission adds a new Docker image
* [ ] This submission fixes a bug (link to related issue: )
* [ ] This submission adds a new feature not listed above

### Testing

* [x] This submission was written on a forked copy of SingleCellOpenProblems
* [ ] GitHub Actions "Run Benchmark" tests are passing on this base branch of this pull request (include link to passed test: )
* [ ] If this pull request is not ready for review (including passing the "Run Benchmark" tests), I will open this PR as a draft (click on the down arrow next to the "Create Pull Request" button)

### Submission guidelines

* [x] This submission follows the guidelines in our [Contributing](../blob/master/CONTRIBUTING.md) document
* [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change

### CODE REVIEW

**Comment by lazappi** [comment]
It looks like the actions are failing because **densmap** is not available. Maybe double check that things are named correctly?

I'm also wondering whether it's better to use the implementation in **umap-learn**? Version 0.5.1 should already be installed so wouldn't have to worry about the docker stuff and this is probably a better maintained package.

**Comment by lazappi** [comment]
Hmmm...build still seems to be failing somewhere in the docker snakemake stage. Might have to ask some of the core people about this.

Maybe double check that you have synched with the latest `master` on the main repo?

**Comment by michalk8** [comment]
This CI was run 18h ago, afaik, the container for `python-extra` was still not fixed then. I think just re-running the jobs should work.

**Comment by lazappi** [comment]
Thanks @michalk8. @bendemeo you might need to merge fetch and merge `master` into here to get the fixes.

**Comment by lazappi** [comment]
@bendemeo Looks like this has completed 🎉 !  Except for the test coverage but not sure exactly how to address that...

Think this is good for now, will look at merging after the pre-processing is sorted out.

**Comment by lazappi** [comment]
@bendemeo Can you please update this to use the pre-processing stuff that has been added to the main repo? Should be able to mostly copy what is in the regular UMAP method https://github.com/singlecellopenproblems/SingleCellOpenProblems/blob/master/openproblems/tasks/dimensionality_reduction/methods/umap.py.

**Comment by lazappi** [comment]
Ping @bendemeo. No pressure but would be great to get an update on this so I can look at submitting stuff to the main repo.

**Comment by lazappi** [comment]
@bendemeo I wanted to wrap these up so I made the changes the merged this locally. Thanks for your contribution 🎉 !

**Pull request merged**
