### PR TITLE
Method neuralee task dimred

### PR DESCRIPTION
**Pull request by michalk8**
### Submission type

* [ ] This submission adds a new dataset
* [x] This submission adds a new method
* [ ] This submission adds a new metric
* [ ] This submission adds a new task
* [ ] This submission adds a new Docker image
* [ ] This submission fixes a bug (link to related issue: )
* [ ] This submission adds a new feature not listed above

### Testing

* [x] This submission was written on a forked copy of SingleCellOpenProblems
* [x] GitHub Actions "Run Benchmark" tests are passing on this base branch of this pull request (include link to passed test: )
  https://github.com/michalk8/SingleCellOpenProblems/actions/runs/702720702
* [x] If this pull request is not ready for review (including passing the "Run Benchmark" tests), I will open this PR as a draft (click on the down arrow next to the "Create Pull Request" button)

### Submission guidelines

* [x] This submission follows the guidelines in our [Contributing](../blob/master/CONTRIBUTING.md) document
* [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change

### CODE REVIEW

**Comment by lazappi** [comment]
🎉  Same as the scvis one. Looks good but I'll hold off merging for now.

**Comment by lazappi** [comment]
Think it's probably fine to keep the pre-processing here as it's part of the method (but feel free to change to the standard function if you think that's appropriate).

**Comment by michalk8** [comment]
Sorry for the late reply @lazappi .I'd keep the preprocessing as it is, alt. I can add `scanpy_preprocessing` as it's done in PHATE's benchmarks.

**Comment by lazappi** [comment]
I'm happy with this, someone can always add the other preprocessing later if it's needed. Thanks for all the updates! Just waiting for the checks but assuming they are all fine should be good to merge all these.

**Pull request merged**
