### PR TITLE
[Dimensional reduction] Adding mouse blood dataset with ground truth from Olsson et al, Nature 2016

### PR DESCRIPTION
**Pull request by mvinyard**
### Submission type

* [x] This submission adds a new dataset
* [ ] This submission adds a new method
* [ ] This submission adds a new metric
* [ ] This submission adds a new task
* [ ] This submission adds a new Docker image
* [ ] This submission fixes a bug (link to related issue: )
* [ ] This submission adds a new feature not listed above

### Testing

* [x] This submission was written on a forked copy of SingleCellOpenProblems
* [ ] GitHub Actions "Run Benchmark" tests are passing on this base branch of this pull request (include link to passed test: )
* [ ] If this pull request is not ready for review (including passing the "Run Benchmark" tests), I will open this PR as a draft (click on the down arrow next to the "Create Pull Request" button)

### Submission guidelines

* [x] This submission follows the guidelines in our [Contributing](../blob/master/CONTRIBUTING.md) document
* [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change

### CODE REVIEW

**Comment by lazappi** [comment]
Thanks, It will be good to have another dataset!

I'm not exactly sure why the check are failing...I did notice a typo in one of the file names though (`"bloud"` instead of `"blood"`). Maybe you can fix that to start with and that should be enough to trigger another action then we can see if we get the same error.

**Comment by mvinyard** [comment]
Thanks @lazappi ! I fixed the typo - hope that resolves it...

**Comment by lazappi** [comment]
Nope 😿 . Possibly this is an upstream issue because it's somewhere in the docker building process which I don't think you have changed. Please double check that you have synched with the latest `master` branch from the main repo. If that doesn't help we might have to ask some of the core people.

**Comment by mvinyard** [comment]
@lazappi I guess we will find out later today

**Comment by lazappi** [comment]
Have you tried merging the current `master` from the main repo?

**Comment by mvinyard** [comment]
@lazappi I think I am confused - I thought we were not supposed to attempt that until later?

**Comment by lazappi** [comment]
So you should merge the `master` branch into your branch (which should fix the issue). Merging things into the main repo will happen later.

**Comment by mvinyard** [comment]
ok I did that @lazappi

**Comment by mvinyard** [comment]
hrm, still failing @lazappi not sure why

**Comment by lazappi** [comment]
@mvinyard It looks like this is passing all the main checks, it's just `precommit` that is failing which is mostly styling stuff. Can you please take a look at that and make the suggested changes? It might also be helpful to install **pre-commit** (`pip install pre-commit` then `pre-commit` install) then run it locally (`pre-commit run --all-files`).

**Comment by lazappi** [comment]
Ping @mvinyard. No pressure but would be great to get an update on this so I can look at submitting stuff to the main repo.

**Comment by mvinyard** [comment]
Thanks for the reminder @lazappi - I'll try to get this done today

**Comment by mvinyard** [comment]
@lazappi I am having a lot of trouble trying to get pre-commit to run. Mostly with the R dependencies. Would you be able to pull my branch real quick and run it, assuming you have a working implementation?

This is what I get after running `pre-commit run --all-files`

```
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
isort....................................................................Passed
black....................................................................Passed
autopep8.................................................................Passed
flake8...................................................................Passed
parsable-R...............................................................Passed
style-files..............................................................Failed
- hook id: style-files
- exit code: 1

Error in library.dynam(lib, package, package.lib) : 
  shared object ‘tibble.dylib’ not found
Calls: eval ... loadNamespace -> namespaceImport -> loadNamespace -> library.dynam
Execution halted

lintr....................................................................Failed
- hook id: lintr
- duration: 0.57s
- exit code: 1

Error in library.dynam(lib, package, package.lib) : 
  shared object ‘stringi.dylib’ not found
Calls: <Anonymous> ... loadNamespace -> namespaceImport -> loadNamespace -> library.dynam
Execution halted
```

Despite having tibble installed. Stringi refuses to install with the other dependencies. Kinda stuck, so I'd appreciate any help you can provide!

**Comment by lazappi** [comment]
No worries, it took me a while to get it working. I ran `pre-commit` locally but looks like I don't have permission to commit back to your master branch 😿. The changes were really easy though so should be able to do them yourself.

```diff
diff --git a/openproblems/data/mouse_blood_olssen_labelled.py b/openproblems/data/mouse_blood_olssen_labelled.py
index 301bf94..6c0ee78 100644
--- a/openproblems/data/mouse_blood_olssen_labelled.py
+++ b/openproblems/data/mouse_blood_olssen_labelled.py
@@ -37,4 +37,3 @@ def load_olsson_2016_mouse_blood(test=False):
             utils.filter_genes_cells(adata)
 
         return adata
-
```

```diff
diff --git a/openproblems/tasks/dimensionality_reduction/datasets/mouse_blood_olssen_labelled.py b/openproblems/tasks/dimensionality_reduction/datasets/mouse_blood_olssen_labelled.py
index e0a4b8a..134554d 100644
--- a/openproblems/tasks/dimensionality_reduction/datasets/mouse_blood_olssen_labelled.py
+++ b/openproblems/tasks/dimensionality_reduction/datasets/mouse_blood_olssen_labelled.py
@@ -2,8 +2,6 @@ from ....data.load_olsson_2016_mouse_blood import load_olsson_2016_mouse_blood
 from ....tools.decorators import dataset
 
 
-@dataset(
-    "Mouse blood. Olsson, et al. Nature. 2016"
-)
+@dataset("Mouse blood. Olsson, et al. Nature. 2016")
 def olsson_2016_mouse_blood(test=False):
     return load_olsson_2016_mouse_blood(test=test)
```

Hopefully those diffs make sense. Alternatively, if it's too hard I can probably merge this and fix the formatting myself seeing as all the actual checks pass.

**Comment by mvinyard** [comment]
@lazappi thanks for your help! that change is super simple - hopefully that's it... lmk if I missed anything. Thanks again for your help

**Comment by lazappi** [comment]
Still failing 😿. I'm also having issues checkout out your changes for some reason so I can't check locally like I did before. It's probably just easier for me to merge this and fix it before I submit to the main repo. Thanks for trying!

**Pull request merged**
